### ISSUE TITLE
Final Jump in Mushroom Parkour is too Far

### ISSUE THREAD

**Issue by jacinta42** [ImTheCactus/Crow-Get-It-Game#38]

**Comment by Emzigma** [comment]
Issue is resolved!

Visual evidence:
![image](https://github.com/ImTheCactus/Crow-Get-It-Game/assets/128340411/7f9638c0-4215-4be3-b576-ced2aeae10e7)

As you can see, the mushroom has been rotated so that the higher part is angled towards the final platform, and the lower part to the previous mushroom. For reference, please ignore the box-collider; it's not being used, it's not even on the model or prefab(s) - it shouldn't even be visible as this prefab uses a mesh collider.

In addition, the duplicate mushroom in this position has been removed.
